---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
      description: The git repository URL
    - name: branch
      type: string
      description: The git branch to build
      default: main
    - name: build-image
      type: string
      description: The image to build
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: init
      taskRef:
        name: echo
      params:
        - name: message
          value: "Starting CD Pipeline..."

    - name: clone
      taskRef:
        name: checkout
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: branch
          value: $(params.branch)
      workspaces:
        - name: source
          workspace: pipeline-workspace
      runAfter:
        - init

    - name: test
      taskRef:
        name: nose
      params:
        - name: database_uri
          value: "postgresql://postgres:pgs3cr3t@postgres:5432/postgres"
        - name: args
          value: "-v --with-spec --spec-color"
      workspaces:
        - name: source
          workspace: pipeline-workspace
      runAfter:
        - clone

    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace
      runAfter:
        - test
